"""add user_asset_detail

Revision ID: 04dda831bca7
Revises: d6c863539047
Create Date: 2023-07-20 16:21:27.430211

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '04dda831bca7'
down_revision = 'd6c863539047'
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ua_detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userasset_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('expiration', sa.Date(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('update_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('meta', sqlite.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['userasset_id'], ['user_asset.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ua_detail_expiration'), 'ua_detail', ['expiration'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ua_detail_expiration'), table_name='ua_detail')
    op.drop_table('ua_detail')
    # ### end Alembic commands ###
