"""alter_fp_code

Revision ID: 0d9669edc1d0
Revises: 836b318f4bfa
Create Date: 2020-01-02 15:09:58.464702

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0d9669edc1d0'
down_revision = '836b318f4bfa'
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('financial_product', 'code', type_=sa.String(length=6),
                    existing_type=mysql.INTEGER(display_width=11))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('financial_product', 'code', type_=sa.Integer(),
                    existing_type=mysql.VARCHAR(length=6))
    # ### end Alembic commands ###
