"""add_user_goal

Revision ID: 1dfa93eea662
Revises: 0d9669edc1d0
Create Date: 2020-01-06 21:29:36.109811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1dfa93eea662'
down_revision = '0d9669edc1d0'
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('goal', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'goal')
    # ### end Alembic commands ###
