"""fk_not_null

Revision ID: 27f75b377203
Revises: 9d2f51a072f2
Create Date: 2019-12-29 16:27:03.612333

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '27f75b377203'
down_revision = '9d2f51a072f2'
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('financial_product', 'type_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('fp_assets', 'fp_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('fp_assets', 'fpa_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('ua_amount', 'userasset_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('user_asset', 'agent_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('user_asset', 'fp',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('user_asset', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_asset', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('user_asset', 'fp',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('user_asset', 'agent_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('ua_amount', 'userasset_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('fp_assets', 'fpa_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('fp_assets', 'fp_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('financial_product', 'type_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    # ### end Alembic commands ###
