"""alter_financial_product

Revision ID: 5ba4d521bbf7
Revises: a95b9e84d76c
Create Date: 2019-12-28 22:35:29.050655

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5ba4d521bbf7'
down_revision = 'a95b9e84d76c'
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fp_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=8), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.drop_column('financial_product', 'type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('financial_product', sa.Column('type', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True))
    op.drop_table('fp_type')
    # ### end Alembic commands ###
