"""userasset_add_is_delete

Revision ID: 836b318f4bfa
Revises: 90fb00a6e774
Create Date: 2019-12-30 22:29:28.144856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '836b318f4bfa'
down_revision = '90fb00a6e774'
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_asset', sa.Column('is_delete', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_asset', 'is_delete')
    # ### end Alembic commands ###
