"""ua_index

Revision ID: 8e30c5ea5de8
Revises: b5a5f259f767
Create Date: 2019-12-29 00:59:09.269897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e30c5ea5de8'
down_revision = 'b5a5f259f767'
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_user_asset_update_time'), 'user_asset', ['update_time'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_asset_update_time'), table_name='user_asset')
    # ### end Alembic commands ###
