"""us_uniq

Revision ID: 90fb00a6e774
Revises: e43b2d6651e2
Create Date: 2019-12-29 17:00:17.153756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90fb00a6e774'
down_revision = 'e43b2d6651e2'
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uix_ag_fp_user', 'user_asset', ['fp', 'agent_id', 'user_id'])
    op.drop_index('uix_fp_user', table_name='user_asset')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uix_fp_user', 'user_asset', ['fp', 'user_id'], unique=True)
    op.drop_constraint('uix_ag_fp_user', 'user_asset', type_='unique')
    # ### end Alembic commands ###
