"""'user_asset-user'

Revision ID: a1d6b04a2fde
Revises: dfe38cbf18b8
Create Date: 2019-12-22 16:33:38.769940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1d6b04a2fde'
down_revision = 'dfe38cbf18b8'
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_asset', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user_asset', 'user', ['user_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_asset', type_='foreignkey')
    op.drop_column('user_asset', 'user_id')
    # ### end Alembic commands ###
