"""alter_financial_product

Revision ID: a95b9e84d76c
Revises: 8e2e0fefe86e
Create Date: 2019-12-28 15:04:58.976118

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a95b9e84d76c'
down_revision = '8e2e0fefe86e'
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('financial_product', sa.Column('code', sa.Integer(), nullable=True))
    op.add_column('financial_product', sa.Column('type', sa.SmallInteger(), nullable=True))
    op.drop_index('fund_code', table_name='financial_product')
    op.drop_index('stock_code', table_name='financial_product')
    op.create_unique_constraint(None, 'financial_product', ['code'])
    op.drop_column('financial_product', 'fund_code')
    op.drop_column('financial_product', 'stock_code')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('financial_product', sa.Column('stock_code', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('financial_product', sa.Column('fund_code', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'financial_product', type_='unique')
    op.create_index('stock_code', 'financial_product', ['stock_code'], unique=True)
    op.create_index('fund_code', 'financial_product', ['fund_code'], unique=True)
    op.drop_column('financial_product', 'type')
    op.drop_column('financial_product', 'code')
    # ### end Alembic commands ###
