"""ty_type_rename

Revision ID: b5a5f259f767
Revises: a45acd478334
Create Date: 2019-12-28 23:21:20.588672

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b5a5f259f767'
down_revision = 'a45acd478334'
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('financial_product', sa.Column('type_id', sa.Integer(), nullable=True))
    op.drop_constraint('financial_product_ibfk_1', 'financial_product', type_='foreignkey')
    op.create_foreign_key(None, 'financial_product', 'fp_type', ['type_id'], ['id'], ondelete='RESTRICT')
    op.drop_column('financial_product', 'type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('financial_product', sa.Column('type', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'financial_product', type_='foreignkey')
    op.create_foreign_key('financial_product_ibfk_1', 'financial_product', 'fp_type', ['type'], ['id'])
    op.drop_column('financial_product', 'type_id')
    # ### end Alembic commands ###
