"""'fp_asset_foreign'

Revision ID: cc3b3a3773fe
Revises: d51ab60b84d2
Create Date: 2019-12-22 16:31:06.369719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc3b3a3773fe'
down_revision = 'd51ab60b84d2'
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fp_assets',
    sa.Column('fp_id', sa.Integer(), nullable=True),
    sa.Column('fpa_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fp_id'], ['financial_product.id'], ),
    sa.ForeignKeyConstraint(['fpa_id'], ['fp_asset.id'], ),
    sa.UniqueConstraint('fp_id', 'fpa_id', name='fp_fpa_unique')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fp_assets')
    # ### end Alembic commands ###
