"""user_add_is_staff

Revision ID: d6c863539047
Revises: 18002047d7cb
Create Date: 2020-01-12 20:56:52.597090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6c863539047'
down_revision = '18002047d7cb'
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_staff', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_staff')
    # ### end Alembic commands ###
