"""us_uniq

Revision ID: e43b2d6651e2
Revises: 27f75b377203
Create Date: 2019-12-29 16:30:30.945457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e43b2d6651e2'
down_revision = '27f75b377203'
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uix_fp_user', 'user_asset', ['fp', 'user_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_fp_user', 'user_asset', type_='unique')
    # ### end Alembic commands ###
